travis:
  secure:
    BINSTAR_TOKEN: RjPkUhSeyOcBv4x6rgSzBkaHWR5JShijcLnZIno4+ae8BwKWiPsKGDdq1UVF8PI7vZD/1462M7K3KRUkYyA5IUsxt6GqYTPtJ8tMAhde7E5voWITo5XYs+q/NDsEMTtlpHFv6okCji7++FtUJzcMkqKJlRHZ5muxfEXDlVv6paruQPjTa+TAGUvp5IkevXXfDF1pouy4P2hGFLn398+UOCv3RxvJQs7DKYDMPfHwRDqMrnOf58p+H/tCA5QLPVD1tEBoTwdtpHhmgDhP2nmPXJc4FQEkMaRPlXYoEnv9oXbU8Gcdb00VM/U680V1TznFyBI6T4ItWaXdgu3HUGgCo3HCTBlE+GkkDISiMToM83uNQum76tKSxxE35sJsi+eEuISL+PvzzFYHp+d6ofVM8sfncnOFZAHecMt3rVQAEFHWzfOwn/uMkOAhv3jAn3ZqNO3cKYo3d6ZJonGlWUfjJ4kg/GvzIxLjdjYsgrpQqwCEbwgxmXdxuBtmfW0a0ZLHxPmAtGqDW2r6p2g/KmMKpUSJk1ojybEiDHh2JYk0rIJdR0yCeBTmhNmXv90OX38WUdE0TidGSO6xz/rQV+mckzwefwqZxnkLUNZf5MzYGbv23HIdtqvkMZDm+KT+Ml0dCW7xdyaeFE3Ejw/n3Us5W49F51dFkhWih7qzPQJsJOk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
